"""Rigid-object configuration for racing gates.

Each gate is a static rigid body composed of four cuboid bars forming a
square opening.  The gate is non-interactive (no dynamics): it is used only
for collision detection and visual reference.

The gate USD is generated by ``scripts/create_gate_usd.py`` and contains
four collidable cuboid bars so the drone can fly through the opening.

Gate geometry (from config/race_config.yaml):
    opening : 1.5 m x 1.5 m
    frame   : 0.1 m thick bars
"""

from __future__ import annotations

import os

import isaaclab.sim as sim_utils
from isaaclab.assets import RigidObjectCfg
from isaaclab.utils import configclass

# ---------------------------------------------------------------------------
# Geometry constants (shared with scripts/create_gate_usd.py)
# ---------------------------------------------------------------------------
GATE_OPENING_W: float = 1.5   # inner width  (m)
GATE_OPENING_H: float = 1.5   # inner height (m)
GATE_THICKNESS: float = 0.1   # frame bar cross-section (m)

# Outer dimensions of the full gate frame
GATE_OUTER_W: float = GATE_OPENING_W + 2.0 * GATE_THICKNESS  # 1.7 m
GATE_OUTER_H: float = GATE_OPENING_H + 2.0 * GATE_THICKNESS  # 1.7 m

# Path to the gate USD (created by scripts/create_gate_usd.py)
_GATE_USD_PATH: str = os.path.join(
    os.path.dirname(__file__), "usd", "racing_gate.usd"
)


@configclass
class RacingGateCfg(RigidObjectCfg):
    """Isaac Lab RigidObjectCfg for a single racing gate."""

    spawn: sim_utils.UsdFileCfg = sim_utils.UsdFileCfg(
        usd_path=_GATE_USD_PATH,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            rigid_body_enabled=True,
            kinematic_enabled=True,   # static body -- no dynamics
            disable_gravity=True,
            max_linear_velocity=0.0,
            max_angular_velocity=0.0,
            linear_damping=0.0,
            angular_damping=0.0,
        ),
        mass_props=sim_utils.MassPropertiesCfg(mass=0.0),
    )

    init_state: RigidObjectCfg.InitialStateCfg = RigidObjectCfg.InitialStateCfg(
        pos=(5.0, 0.0, 1.5),
        rot=(1.0, 0.0, 0.0, 0.0),
    )


# Convenience instance
RACING_GATE_CFG = RacingGateCfg()
